### ISSUE TITLE
Support ingressClassName along side kubernetes.io/ingress.class

### ISSUE THREAD

**Issue by krokofant** [featbit/featbit-charts#18]
The [AGW ingress controller](https://azure.github.io/application-gateway-kubernetes-ingress/ingress-v1/) still uses `kubernetes.io/ingress.class` but the AWS ALB ingress controller doesn't use it anymore but only uses ingressClassName.

Via the helm chart there is no way of setting ingressClassName of the ingress.

**Comment by dsun0720** [comment]
@krokofant Thank you for your advice. I' ll add `ingressClassName` in the next release

**Comment by dsun0720** [comment]
This issue is fixed in in the v0.0.7
