### ISSUE TITLE
Expose podLabels for redis and das-test-connection

### ISSUE THREAD

**Issue by krokofant** [featbit/featbit-charts#20]
If labels for das-test-connections are exposed it will be easier to match against this pod to configure firewall rules.
https://github.com/featbit/featbit-charts/blob/main/charts/featbit/templates/tests/das-test-connection.yaml

Edit: podLabels for redis are also missing

**Comment by dsun0720** [comment]
@krokofant this yaml is a unit test for testing whether da-server has started correctly.
